app = "ohm"
kill_signal = "SIGINT"
kill_timeout = "5s"

[build]
  builder = "paketobuildpacks/builder:base"
  buildpacks = ["gcr.io/paketo-buildpacks/go"]

[metrics]
  port = 9091
  path = "/metrics"

[deploy]
  strategy = "immediate"

[experimental]
  allowed_public_ports = []
  auto_rollback = false
