name: Go

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.18
    - name: Prepare for Build
      run: cp example-config.yaml cmd/ohm/config.yaml
    - name: Test
      run: go test -v ./...
    - name: golangci-lint
      uses: golangci/golangci-lint-action@v3
